# Proxy (Upstream) Server
bindAddress: "0.0.0.0"
port: 25565
motd: "Barrel Classic Connect to Bedrock Server"
# max players in proxy
maxplayers: 10
# Message when the proxy is closed
shutdownMessage: "Proxy Closed"
# Is Player ClassiCube account
premiumPlayerClassic: false

# Downstream server (bedrock)
bedrockAddress: "join.servermc.xyz"
bedrockPort: 10171
# Use xbox login? (offline|online)
auth: online
